/* Generated by scripts/generate-weather-icons.mjs.
ISC License

Copyright (c) 2026 Lucide Icons and Contributors

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

---

The following Lucide icons are derived from the Feather project:

airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out

The MIT License (MIT) (for the icons listed above)

Copyright (c) 2013-present Cole Bemis

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
export const weatherIcons = {
  sun: [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '4',
      },
    ],
    [
      'path',
      {
        d: 'M12 2v2',
      },
    ],
    [
      'path',
      {
        d: 'M12 20v2',
      },
    ],
    [
      'path',
      {
        d: 'm4.93 4.93 1.41 1.41',
      },
    ],
    [
      'path',
      {
        d: 'm17.66 17.66 1.41 1.41',
      },
    ],
    [
      'path',
      {
        d: 'M2 12h2',
      },
    ],
    [
      'path',
      {
        d: 'M20 12h2',
      },
    ],
    [
      'path',
      {
        d: 'm6.34 17.66-1.41 1.41',
      },
    ],
    [
      'path',
      {
        d: 'm19.07 4.93-1.41 1.41',
      },
    ],
  ],
  moon: [
    [
      'path',
      {
        d: 'M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401',
      },
    ],
  ],
  'cloud-sun': [
    [
      'path',
      {
        d: 'M12 2v2',
      },
    ],
    [
      'path',
      {
        d: 'm4.93 4.93 1.41 1.41',
      },
    ],
    [
      'path',
      {
        d: 'M20 12h2',
      },
    ],
    [
      'path',
      {
        d: 'm19.07 4.93-1.41 1.41',
      },
    ],
    [
      'path',
      {
        d: 'M15.947 12.65a4 4 0 0 0-5.925-4.128',
      },
    ],
    [
      'path',
      {
        d: 'M13 22H7a5 5 0 1 1 4.9-6H13a3 3 0 0 1 0 6Z',
      },
    ],
  ],
  'cloud-moon': [
    [
      'path',
      {
        d: 'M13 16a3 3 0 0 1 0 6H7a5 5 0 1 1 4.9-6z',
      },
    ],
    [
      'path',
      {
        d: 'M18.376 14.512a6 6 0 0 0 3.461-4.127c.148-.625-.659-.97-1.248-.714a4 4 0 0 1-5.259-5.26c.255-.589-.09-1.395-.716-1.248a6 6 0 0 0-4.594 5.36',
      },
    ],
  ],
  cloud: [
    [
      'path',
      {
        d: 'M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z',
      },
    ],
  ],
  cloudy: [
    [
      'path',
      {
        d: 'M17.5 12a1 1 0 1 1 0 9H9.006a7 7 0 1 1 6.702-9z',
      },
    ],
    [
      'path',
      {
        d: 'M21.832 9A3 3 0 0 0 19 7h-2.207a5.5 5.5 0 0 0-10.72.61',
      },
    ],
  ],
  'cloud-fog': [
    [
      'path',
      {
        d: 'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242',
      },
    ],
    [
      'path',
      {
        d: 'M16 17H7',
      },
    ],
    [
      'path',
      {
        d: 'M17 21H9',
      },
    ],
  ],
  haze: [
    [
      'path',
      {
        d: 'm5.2 6.2 1.4 1.4',
      },
    ],
    [
      'path',
      {
        d: 'M2 13h2',
      },
    ],
    [
      'path',
      {
        d: 'M20 13h2',
      },
    ],
    [
      'path',
      {
        d: 'm17.4 7.6 1.4-1.4',
      },
    ],
    [
      'path',
      {
        d: 'M22 17H2',
      },
    ],
    [
      'path',
      {
        d: 'M22 21H2',
      },
    ],
    [
      'path',
      {
        d: 'M16 13a4 4 0 0 0-8 0',
      },
    ],
    [
      'path',
      {
        d: 'M12 5V2.5',
      },
    ],
  ],
  'cloud-drizzle': [
    [
      'path',
      {
        d: 'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242',
      },
    ],
    [
      'path',
      {
        d: 'M8 19v1',
      },
    ],
    [
      'path',
      {
        d: 'M8 14v1',
      },
    ],
    [
      'path',
      {
        d: 'M16 19v1',
      },
    ],
    [
      'path',
      {
        d: 'M16 14v1',
      },
    ],
    [
      'path',
      {
        d: 'M12 21v1',
      },
    ],
    [
      'path',
      {
        d: 'M12 16v1',
      },
    ],
  ],
  'cloud-rain': [
    [
      'path',
      {
        d: 'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242',
      },
    ],
    [
      'path',
      {
        d: 'M16 14v6',
      },
    ],
    [
      'path',
      {
        d: 'M8 14v6',
      },
    ],
    [
      'path',
      {
        d: 'M12 16v6',
      },
    ],
  ],
  'cloud-rain-wind': [
    [
      'path',
      {
        d: 'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242',
      },
    ],
    [
      'path',
      {
        d: 'm9.2 22 3-7',
      },
    ],
    [
      'path',
      {
        d: 'm9 13-3 7',
      },
    ],
    [
      'path',
      {
        d: 'm17 13-3 7',
      },
    ],
  ],
  'cloud-lightning': [
    [
      'path',
      {
        d: 'M6 16.326A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 .5 8.973',
      },
    ],
    [
      'path',
      {
        d: 'm13 12-3 5h4l-3 5',
      },
    ],
  ],
  'cloud-snow': [
    [
      'path',
      {
        d: 'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242',
      },
    ],
    [
      'path',
      {
        d: 'M8 15h.01',
      },
    ],
    [
      'path',
      {
        d: 'M8 19h.01',
      },
    ],
    [
      'path',
      {
        d: 'M12 17h.01',
      },
    ],
    [
      'path',
      {
        d: 'M12 21h.01',
      },
    ],
    [
      'path',
      {
        d: 'M16 15h.01',
      },
    ],
    [
      'path',
      {
        d: 'M16 19h.01',
      },
    ],
  ],
  'cloud-hail': [
    [
      'path',
      {
        d: 'M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242',
      },
    ],
    [
      'path',
      {
        d: 'M16 14v2',
      },
    ],
    [
      'path',
      {
        d: 'M8 14v2',
      },
    ],
    [
      'path',
      {
        d: 'M16 20h.01',
      },
    ],
    [
      'path',
      {
        d: 'M8 20h.01',
      },
    ],
    [
      'path',
      {
        d: 'M12 16v2',
      },
    ],
    [
      'path',
      {
        d: 'M12 22h.01',
      },
    ],
  ],
  wind: [
    [
      'path',
      {
        d: 'M12.8 19.6A2 2 0 1 0 14 16H2',
      },
    ],
    [
      'path',
      {
        d: 'M17.5 8a2.5 2.5 0 1 1 2 4H2',
      },
    ],
    [
      'path',
      {
        d: 'M9.8 4.4A2 2 0 1 1 11 8H2',
      },
    ],
  ],
  tornado: [
    [
      'path',
      {
        d: 'M21 4H3',
      },
    ],
    [
      'path',
      {
        d: 'M18 8H6',
      },
    ],
    [
      'path',
      {
        d: 'M19 12H9',
      },
    ],
    [
      'path',
      {
        d: 'M16 16h-6',
      },
    ],
    [
      'path',
      {
        d: 'M11 20H9',
      },
    ],
  ],
  'circle-question-mark': [
    [
      'circle',
      {
        cx: '12',
        cy: '12',
        r: '10',
      },
    ],
    [
      'path',
      {
        d: 'M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3',
      },
    ],
    [
      'path',
      {
        d: 'M12 17h.01',
      },
    ],
  ],
};
